/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "yi-ui",
  "description": "ui 库",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Button 组件",
      "frontmatter": {},
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-399704cf",
      "path": "/components/button.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "欢迎 →",
        "actionLink": "/components/button",
        "features": [
          {
            "title": "yi-ui 官方文档",
            "details": "yi-ui 官方文档"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-28893bb9",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      }
    ],
    "sidebar": [
      {
        "title": "介绍",
        "collapsable": true,
        "children": [
          "/introduce/"
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "children": [
          "/components/button"
        ]
      }
    ]
  }
}